### ISSUE TITLE
sir please can i get your help 

### ISSUE THREAD

**Issue by ghost** [sandymanu/device_nougathammer#9]
sir can you please compile lineage 15 for me 
my device tree: https://github.com/lineage-15-land/android_device_xiaomi_land.git
kernel tree : https://github.com/XPerience-AOSP-Lollipop/android_kernel_xiaomi_msm8937.git -b xpe-12.0
vendor tree: https://github.com/lineage-15-land/proprietary_vendor_xiaomi.git
please sir i want to contribute to hammerhead and my device redmi 3s

**Comment by sandymanu** [comment]
Sorry,no
